variables:
  windows_vm: windows-2019
  ubuntu_vm: ubuntu-22.04
  macos_vm: macOS-12
  ci_runner_image: trini/u-boot-gitlab-ci-runner:jammy-20240227-14Mar2024
  # Add '-u 0' options for Azure pipelines, otherwise we get "permission
  # denied" error when it tries to "useradd -m -u 1001 vsts_azpcontainer",
  # since our $(ci_runner_image) user is not root.
  container_option: -u 0
  work_dir: /u

stages:
- stage: world_build
  jobs:
  - job: build_the_world
    timeoutInMinutes: 0 # Use the maximum allowed
    displayName: 'Build the World'
    pool:
      vmImage: $(ubuntu_vm)
    strategy:
      # Use almost the same target division in .travis.yml, only merged
      # 3 small build jobs (arc/microblaze/xtensa) into one.
      matrix:
        am33xx_at91_kirkwood_mvebu_omap:
          BUILDMAN: "am33xx at91_kirkwood mvebu omap -x siemens"
          name: am33xx_at91_kirkwood_mvebu_omap
        amlogic_bcm_boundary_engicam_siemens_technexion_oradex:
          BUILDMAN: "amlogic bcm boundary engicam siemens technexion toradex -x mips"
          name: amlogic_bcm_boundary_engicam_siemens_technexion_oradex
        arm_nxp_minus_imx:
          BUILDMAN: "freescale -x powerpc,m68k,imx,mx"
          name: arm_nxp_minus_imx
        imx:
          BUILDMAN: "mx imx -x boundary,engicam,technexion,toradex"
          name: imx
        rk:
          BUILDMAN: "rk"
          name: rk
        sunxi:
          BUILDMAN: "sunxi"
          name: sunxi
        powerpc:
          BUILDMAN: "powerpc"
          name: powerpc
        arm_catch_all:
          BUILDMAN: "arm -x aarch64,am33xx,at91,bcm,ls1,kirkwood,mvebu,omap,rk,siemens,mx,sunxi,technexion,toradex"
          name: arm_catch_all
        aarch64_catch_all:
          BUILDMAN: "aarch64 -x amlogic,bcm,engicam,imx,ls1,ls2,lx216,mvebu,rk,siemens,sunxi,toradex"
          name: aarch64_catch_all
        everything_but_arm_and_powerpc:
          BUILDMAN: "-x arm,powerpc"
          name: everything_but_arm_and_powerpc
    steps:
      - script: |
          cat << EOF > build.sh
          set -ex
          cd ${WORK_DIR}
          # make environment variables available as tests are running inside a container
          export BUILDMAN="${BUILDMAN}"
          git config --global --add safe.directory ${WORK_DIR}
          pip install -r tools/buildman/requirements.txt
          EOF
          cat << "EOF" >> build.sh
          echo $(System.JobName)
          echo "##vso[task.setvariable variable=myStageVal;isoutput=true]this is a stage output variable .$(System.JobName)."
          if [[ "${BUILDMAN}" != "" ]]; then
              ret=0;
              echo "##vso[task.setvariable variable=boards;isOutput=true]$(tools/buildman/buildman -o /tmp --dry-run -v ${BUILDMAN} | grep -E '^   ' | tr '\n' ' ')";
          fi
          EOF
          cat build.sh
          docker run -v $PWD:$(work_dir) $(ci_runner_image) /bin/bash $(work_dir)/build.sh
        name: $[ System.JobName ]

- stage: count_em_all
  dependsOn: world_build
  jobs:
    - job: count_all_boards
      pool:
        vmImage: $(ubuntu_vm)
      variables:
        allboards: $[stageDependencies.world_build.rk.outputs['rk.boards']]
      steps:
        # 6 extra lines
        - bash: echo == ${allboards} == ${myStageVal} == $(System.PhaseName) ==
